import 'package:movie_app/domain/models/person/person.dart';

List<Person> personList = [

  Person(
    id: 587506,
    name: "Shameik Moore",
    biography: "Shameik Alti Moore (born May 4, 1995) is an American actor, singer, and rapper, of Jamaican descent.\n\nHe started off with bit roles on shows such as Tyler Perry's House of Payne, Reed Between the Lines, and Joyful Noise. In 2013, he had his first main television role on the sketch-comedy series Incredible Crew, which aired on Cartoon Network before being cancelled after one season.\n\nHe then gained recognition with his portrayal of Malcolm in the 2015 film Dope, which premiered at the 2015 Sundance Film Festival. Indiewire included Moore on its list of \"The 12 Major Breakouts of the 2015 Sundance Film Festival\" for his performance in the movie.\n\nHe is also one of the five male leads in the Netflix series The Get Down, which premiered in 2016 and was cancelled in 2017 after one half-season. He voiced Miles Morales in the animated film Spider-Man: Into the Spider-Verse from Sony Pictures Animation, which was released in December 2018.",
  ),
  Person(
    id: 2372,
    name: "Ron Perlman",
    biography: "Ronald Perlman (born April 13, 1950) is an American actor and voice-over actor. His best known roles are as Clay Morrow on Sons of Anarchy (2008–2013), Hellboy in Hellboy (2004) and its sequel Hellboy II: The Golden Army (2008), Vincent on the series Beauty and the Beast (1987–1990) for which he won a Golden Globe Award, Salvatore in The Name of the Rose (1986), Johner in Alien Resurrection (1997), Nino in Drive (2011), and Benedict Drask in Don't Look Up (2021).\n\nPerlman is also known as a collaborator of Hellboy director Guillermo del Toro, having roles in the del Toro films Cronos (1993), Blade II (2002), Pacific Rim (2013) and Nightmare Alley (2021). His voice-over work includes the narrator of the post-apocalyptic game series Fallout (1997–present), Clayface in the DC Animated Universe, Slade in Teen Titans (2003–2006), Mr. Lancer in Danny Phantom (2004–2007), Lord Hood in the video games Halo 2 (2004) and Halo 3 (2007), the Stabbington brothers in Tangled (2010), The Lich in Adventure Time (2011–2017), Xibalba in The Book of Life (2014) and Optimus Prime in both the Transformers: Power of the Primes (2018) animated series, and the film Transformers: Rise of the Beasts (2023).",
  ),

  Person(
    id: 234352,
    name: "Margot Robbie",
    biography: "Margot Elise Robbie (born July 2, 1990) is an Australian actress and producer. Known for her work in both blockbuster and independent films, she has received several accolades, including nominations for two Academy Awards, four Golden Globe Awards, and five British Academy Film Awards. Time magazine named her one of the 100 most influential people in the world in 2017 and she was ranked as one of the world's highest-paid actresses by Forbes in 2019.\n\nBorn and raised in Queensland, Robbie began her career in 2008 on the television series Neighbours, on which she was a regular until 2011. After moving to America, she led the television series Pan Am (2011–2012), and had her breakthrough in 2013 with the black comedy film The Wolf of Wall Street. She achieved wider recognition with starring roles as Jane Porter in The Legend of Tarzan (2016), Harley Quinn in the DC superhero films Suicide Squad (2016), Birds of Prey (2020) and The Suicide Squad (2021), and the title role of Barbie in Barbie (2023).\n\nRobbie received critical acclaim and a nomination for the Academy Award for Best Actress for her portrayal of disgraced figure skater Tonya Harding in the biopic I, Tonya (2017). This acclaim continued with her roles as Queen Elizabeth I in the period drama Mary Queen of Scots (2018), Sharon Tate in the comedy-drama Once Upon a Time in Hollywood (2019), and a fictional Fox News employee in the drama Bombshell (2019); she received BAFTA Award nominations for all three and a nomination for the Academy Award for Best Supporting Actress for the lattermost.\n\nRobbie is married to filmmaker Tom Ackerley. They are co-founders of the production company LuckyChap Entertainment, under which they have produced several films, including I, Tonya and Promising Young Woman (2020), as well as the television series Dollface (2019–2022) and the miniseries Maid (2021).",
  ),
];